create database try;
use try;
show databases;
create table student (stdid int primary key, rollno  int,mark int, age int,firstname varchar(10),check(age>=20));
desc student;
insert into student values(1,11,50,21,'omkar');
insert into student values(2,11,50,21,'yogesh');
insert into student values(3,11,50,21,'yash');
insert into student values(4,11,50,20,'yogesh');
select * from student;
update student set rollno=10 where stdid=1;
update student set rollno=20 where stdid=3;
alter table student drop column mark;
alter table student add column mark varchar(10);
alter table student add constraint chk_mark check(mark>=35);
update student set mark=39 where stdid=1; 
update student set mark=45 where stdid=2;
update student set mark=60 where stdid=3;
alter table student drop check chk_mark;
update student set mark=30 where stdid=4;
alter table student drop check student_chk_2;
truncate table student;
select * from student;
drop table student;
